language: bash

services:
  - docker

env:
  matrix:
    - DRUPAL_VER=8 NGINX_VER=1.15 TAGS=8-1.15,1.15,8,latest
    - DRUPAL_VER=7 NGINX_VER=1.15 TAGS=7-1.15,7
    - DRUPAL_VER=6 NGINX_VER=1.15 TAGS=6-1.15,6
    - DRUPAL_VER=8 NGINX_VER=1.14 TAGS=8-1.14,1.14
    - DRUPAL_VER=7 NGINX_VER=1.14 TAGS=7-1.14
    - DRUPAL_VER=6 NGINX_VER=1.14 TAGS=6-1.14
    - DRUPAL_VER=8 NGINX_VER=1.13 TAGS=8-1.13,1.13
    - DRUPAL_VER=7 NGINX_VER=1.13 TAGS=7-1.13
    - DRUPAL_VER=6 NGINX_VER=1.13 TAGS=6-1.13

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
